In [186]:
import numpy as np
import pandas as pd

In [187]:
arr=np.arange(4)
print(arr)

[0 1 2 3]


In [188]:
dict={'a':1,'b':2,'c':3,'d':4}

In [189]:
labels=['w','x','y','z']

In [190]:
list1=[12,23,3,4]

In [191]:
pd.Series(arr)

0    0
1    1
2    2
3    3
dtype: int32

In [192]:
pd.Series(arr,labels)   # or pd.Series(data=arr,index=label)

w    0
x    1
y    2
z    3
dtype: int32

In [193]:
labels2=['w','x','y','z','a']

pd.Series(arr,labels2)# it will give error as length of label and the list or any other thing must be same

In [194]:
pd.Series(dict)

a    1
b    2
c    3
d    4
dtype: int64

In [195]:
pd.Series(list1)

0    12
1    23
2     3
3     4
dtype: int64

In [196]:
tup=(1,2,3,4)


In [197]:
pd.Series(tup)

0    1
1    2
2    3
3    4
dtype: int64

pandas slicing in series

In [198]:
sports1=pd.Series([1,2,3,4],['cricket','football','vollyball','golf'])

In [199]:
print(sports1)

cricket      1
football     2
vollyball    3
golf         4
dtype: int64


In [200]:
print(sports1['cricket'])
print(sports1[0])
#BOTH WILL GIVE SAME VALUE

1
1


In [201]:
sports2=pd.Series([2,3,4,1],['cricket','chess','vollyball','pubg'])

In [202]:
sports2

cricket      2
chess        3
vollyball    4
pubg         1
dtype: int64

In [203]:
sports1+sports2

chess        NaN
cricket      3.0
football     NaN
golf         NaN
pubg         NaN
vollyball    7.0
dtype: float64

In [204]:
sports1*sports2
# we are doing the operation on the basis of index value

chess         NaN
cricket       2.0
football      NaN
golf          NaN
pubg          NaN
vollyball    12.0
dtype: float64

In [205]:
np.random.seed(0)# we use seed to always get the same values in rand fuction

In [206]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [207]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [208]:
dataframe=pd.DataFrame(np.random.randn(10,5),index='A B C D E F G H I J'.split(),columns='sub1 sub2 sub3 sub4 sub5'.split())

In [209]:
print(dataframe)

       sub1      sub2      sub3      sub4      sub5
A -0.842724  1.969924  1.266119 -0.505877  2.545201
B  1.080812  0.484312  0.579140 -0.181583  1.410205
C -0.374472  0.275198 -0.960755  0.376927  0.033439
D  0.680567 -1.563497 -0.566698 -0.242150  1.514391
E -0.333057  0.047365  1.462740  1.535029  0.566440
F  0.149265 -1.078278  1.395472  1.787484 -0.569517
G  0.175387 -0.462506 -1.085801  0.639736 -0.385863
H -0.775762  0.995711 -1.933205  0.248531 -0.031245
I -0.139474 -0.190656  0.448638 -0.992430 -0.225940
J -1.654571 -0.639723 -0.479420  0.311364 -0.776020


Indexing in pandas

In [210]:
dataframe['sub1']

A   -0.842724
B    1.080812
C   -0.374472
D    0.680567
E   -0.333057
F    0.149265
G    0.175387
H   -0.775762
I   -0.139474
J   -1.654571
Name: sub1, dtype: float64

In [211]:
dataframe[['sub1','sub2']]

sub1      sub2
A -0.842724  1.969924
B  1.080812  0.484312
C -0.374472  0.275198
D  0.680567 -1.563497
E -0.333057  0.047365
F  0.149265 -1.078278
G  0.175387 -0.462506
H -0.775762  0.995711
I -0.139474 -0.190656
J -1.654571 -0.639723

In [212]:
dataframe[['sub2','sub1']]

sub2      sub1
A  1.969924 -0.842724
B  0.484312  1.080812
C  0.275198 -0.374472
D -1.563497  0.680567
E  0.047365 -0.333057
F -1.078278  0.149265
G -0.462506  0.175387
H  0.995711 -0.775762
I -0.190656 -0.139474
J -0.639723 -1.654571

In [213]:
dataframe['sub6']=dataframe['sub2']+dataframe['sub3']#ading a new column

In [214]:
print(dataframe)

       sub1      sub2      sub3      sub4      sub5      sub6
A -0.842724  1.969924  1.266119 -0.505877  2.545201  3.236043
B  1.080812  0.484312  0.579140 -0.181583  1.410205  1.063453
C -0.374472  0.275198 -0.960755  0.376927  0.033439 -0.685556
D  0.680567 -1.563497 -0.566698 -0.242150  1.514391 -2.130194
E -0.333057  0.047365  1.462740  1.535029  0.566440  1.510105
F  0.149265 -1.078278  1.395472  1.787484 -0.569517  0.317194
G  0.175387 -0.462506 -1.085801  0.639736 -0.385863 -1.548306
H -0.775762  0.995711 -1.933205  0.248531 -0.031245 -0.937493
I -0.139474 -0.190656  0.448638 -0.992430 -0.225940  0.257982
J -1.654571 -0.639723 -0.479420  0.311364 -0.776020 -1.119142


In [215]:
dataframe.drop('A')

sub1      sub2      sub3      sub4      sub5      sub6
B  1.080812  0.484312  0.579140 -0.181583  1.410205  1.063453
C -0.374472  0.275198 -0.960755  0.376927  0.033439 -0.685556
D  0.680567 -1.563497 -0.566698 -0.242150  1.514391 -2.130194
E -0.333057  0.047365  1.462740  1.535029  0.566440  1.510105
F  0.149265 -1.078278  1.395472  1.787484 -0.569517  0.317194
G  0.175387 -0.462506 -1.085801  0.639736 -0.385863 -1.548306
H -0.775762  0.995711 -1.933205  0.248531 -0.031245 -0.937493
I -0.139474 -0.190656  0.448638 -0.992430 -0.225940  0.257982
J -1.654571 -0.639723 -0.479420  0.311364 -0.776020 -1.119142

In [216]:
dataframe

sub1      sub2      sub3      sub4      sub5      sub6
A -0.842724  1.969924  1.266119 -0.505877  2.545201  3.236043
B  1.080812  0.484312  0.579140 -0.181583  1.410205  1.063453
C -0.374472  0.275198 -0.960755  0.376927  0.033439 -0.685556
D  0.680567 -1.563497 -0.566698 -0.242150  1.514391 -2.130194
E -0.333057  0.047365  1.462740  1.535029  0.566440  1.510105
F  0.149265 -1.078278  1.395472  1.787484 -0.569517  0.317194
G  0.175387 -0.462506 -1.085801  0.639736 -0.385863 -1.548306
H -0.775762  0.995711 -1.933205  0.248531 -0.031245 -0.937493
I -0.139474 -0.190656  0.448638 -0.992430 -0.225940  0.257982
J -1.654571 -0.639723 -0.479420  0.311364 -0.776020 -1.119142

In [217]:
# if we want to permanent delete the raow ten-
dataframe.drop('A',inplace=True)

In [218]:
dataframe

sub1      sub2      sub3      sub4      sub5      sub6
B  1.080812  0.484312  0.579140 -0.181583  1.410205  1.063453
C -0.374472  0.275198 -0.960755  0.376927  0.033439 -0.685556
D  0.680567 -1.563497 -0.566698 -0.242150  1.514391 -2.130194
E -0.333057  0.047365  1.462740  1.535029  0.566440  1.510105
F  0.149265 -1.078278  1.395472  1.787484 -0.569517  0.317194
G  0.175387 -0.462506 -1.085801  0.639736 -0.385863 -1.548306
H -0.775762  0.995711 -1.933205  0.248531 -0.031245 -0.937493
I -0.139474 -0.190656  0.448638 -0.992430 -0.225940  0.257982
J -1.654571 -0.639723 -0.479420  0.311364 -0.776020 -1.119142

In [219]:
dataframe.drop('sub4',axis=1)#we use axis=1 to delete column and axis=0 or nothing to delete a row

sub1      sub2      sub3      sub5      sub6
B  1.080812  0.484312  0.579140  1.410205  1.063453
C -0.374472  0.275198 -0.960755  0.033439 -0.685556
D  0.680567 -1.563497 -0.566698  1.514391 -2.130194
E -0.333057  0.047365  1.462740  0.566440  1.510105
F  0.149265 -1.078278  1.395472 -0.569517  0.317194
G  0.175387 -0.462506 -1.085801 -0.385863 -1.548306
H -0.775762  0.995711 -1.933205 -0.031245 -0.937493
I -0.139474 -0.190656  0.448638 -0.225940  0.257982
J -1.654571 -0.639723 -0.479420 -0.776020 -1.119142

In [220]:
dataframe#here we notice that we get the original dataframe even after deleting 

sub1      sub2      sub3      sub4      sub5      sub6
B  1.080812  0.484312  0.579140 -0.181583  1.410205  1.063453
C -0.374472  0.275198 -0.960755  0.376927  0.033439 -0.685556
D  0.680567 -1.563497 -0.566698 -0.242150  1.514391 -2.130194
E -0.333057  0.047365  1.462740  1.535029  0.566440  1.510105
F  0.149265 -1.078278  1.395472  1.787484 -0.569517  0.317194
G  0.175387 -0.462506 -1.085801  0.639736 -0.385863 -1.548306
H -0.775762  0.995711 -1.933205  0.248531 -0.031245 -0.937493
I -0.139474 -0.190656  0.448638 -0.992430 -0.225940  0.257982
J -1.654571 -0.639723 -0.479420  0.311364 -0.776020 -1.119142

In [221]:
#to remove the column permanently we uses a inplace in our drop function
dataframe.drop('sub5',axis=1,inplace=True)

In [222]:
dataframe

sub1      sub2      sub3      sub4      sub6
B  1.080812  0.484312  0.579140 -0.181583  1.063453
C -0.374472  0.275198 -0.960755  0.376927 -0.685556
D  0.680567 -1.563497 -0.566698 -0.242150 -2.130194
E -0.333057  0.047365  1.462740  1.535029  1.510105
F  0.149265 -1.078278  1.395472  1.787484  0.317194
G  0.175387 -0.462506 -1.085801  0.639736 -1.548306
H -0.775762  0.995711 -1.933205  0.248531 -0.937493
I -0.139474 -0.190656  0.448638 -0.992430  0.257982
J -1.654571 -0.639723 -0.479420  0.311364 -1.119142

In [223]:
# to remove a row we just use
dataframe.drop('C',axis=0)


sub1      sub2      sub3      sub4      sub6
B  1.080812  0.484312  0.579140 -0.181583  1.063453
D  0.680567 -1.563497 -0.566698 -0.242150 -2.130194
E -0.333057  0.047365  1.462740  1.535029  1.510105
F  0.149265 -1.078278  1.395472  1.787484  0.317194
G  0.175387 -0.462506 -1.085801  0.639736 -1.548306
H -0.775762  0.995711 -1.933205  0.248531 -0.937493
I -0.139474 -0.190656  0.448638 -0.992430  0.257982
J -1.654571 -0.639723 -0.479420  0.311364 -1.119142

In [224]:
dataframe

sub1      sub2      sub3      sub4      sub6
B  1.080812  0.484312  0.579140 -0.181583  1.063453
C -0.374472  0.275198 -0.960755  0.376927 -0.685556
D  0.680567 -1.563497 -0.566698 -0.242150 -2.130194
E -0.333057  0.047365  1.462740  1.535029  1.510105
F  0.149265 -1.078278  1.395472  1.787484  0.317194
G  0.175387 -0.462506 -1.085801  0.639736 -1.548306
H -0.775762  0.995711 -1.933205  0.248531 -0.937493
I -0.139474 -0.190656  0.448638 -0.992430  0.257982
J -1.654571 -0.639723 -0.479420  0.311364 -1.119142

In [225]:
dataframe.loc['B']

sub1    1.080812
sub2    0.484312
sub3    0.579140
sub4   -0.181583
sub6    1.063453
Name: B, dtype: float64

In [226]:
dataframe.iloc[1]#iloc for the normal indexing

sub1   -0.374472
sub2    0.275198
sub3   -0.960755
sub4    0.376927
sub6   -0.685556
Name: C, dtype: float64

In [227]:
dataframe.loc['B','sub1']#to get a perticular value

1.0808119130554454

In [228]:
dataframe.loc[['C','E'],['sub3','sub1']]#subsetting by selection methos

sub3      sub1
C -0.960755 -0.374472
E  1.462740 -0.333057

In [229]:
dataframe>0.7#gives us the boolean value of data is either biger or lesser than the given data

sub1   sub2   sub3   sub4   sub6
B   True  False  False  False   True
C  False  False  False  False  False
D  False  False  False  False  False
E  False  False   True   True   True
F  False  False   True   True  False
G  False  False  False  False  False
H  False   True  False  False  False
I  False  False  False  False  False
J  False  False  False  False  False

In [230]:
#to get the value instead of the boolean data we can do it as-
dataframe[dataframe>0.5]

sub1      sub2      sub3      sub4      sub6
B  1.080812       NaN  0.579140       NaN  1.063453
C       NaN       NaN       NaN       NaN       NaN
D  0.680567       NaN       NaN       NaN       NaN
E       NaN       NaN  1.462740  1.535029  1.510105
F       NaN       NaN  1.395472  1.787484       NaN
G       NaN       NaN       NaN  0.639736       NaN
H       NaN  0.995711       NaN       NaN       NaN
I       NaN       NaN       NaN       NaN       NaN
J       NaN       NaN       NaN       NaN       NaN

In [231]:
#to a perticular column in a dataframe
dataframe[dataframe['sub3']>.8]#shows data of the column in which the value of given column is greater than the given data

sub1      sub2      sub3      sub4      sub6
E -0.333057  0.047365  1.462740  1.535029  1.510105
F  0.149265 -1.078278  1.395472  1.787484  0.317194

In [232]:
dataframe[dataframe['sub3']>.8]['sub2']#giving the value of sub2 only

E    0.047365
F   -1.078278
Name: sub2, dtype: float64

In [233]:
dataframe.loc['C']

sub1   -0.374472
sub2    0.275198
sub3   -0.960755
sub4    0.376927
sub6   -0.685556
Name: C, dtype: float64

In [245]:
dataframe.reset_index(inplace=True)

In [247]:
dataframe.iloc[0]

index           B
sub1      1.08081
sub2     0.484312
sub3      0.57914
sub4    -0.181583
sub6      1.06345
Name: 0, dtype: object

In [248]:
dataframe

index      sub1      sub2      sub3      sub4      sub6
0     B  1.080812  0.484312  0.579140 -0.181583  1.063453
1     C -0.374472  0.275198 -0.960755  0.376927 -0.685556
2     D  0.680567 -1.563497 -0.566698 -0.242150 -2.130194
3     E -0.333057  0.047365  1.462740  1.535029  1.510105
4     F  0.149265 -1.078278  1.395472  1.787484  0.317194
5     G  0.175387 -0.462506 -1.085801  0.639736 -1.548306
6     H -0.775762  0.995711 -1.933205  0.248531 -0.937493
7     I -0.139474 -0.190656  0.448638 -0.992430  0.257982
8     J -1.654571 -0.639723 -0.479420  0.311364 -1.119142

In [255]:
new_index="in sr pak nep ch bh jpn ame rus".split()

In [256]:
dataframe['countries']=new_index

In [259]:
dataframe.set_index('countries',inplace=True)

In [260]:
dataframe

index      sub1      sub2      sub3      sub4      sub6
countries                                                        
in            B  1.080812  0.484312  0.579140 -0.181583  1.063453
sr            C -0.374472  0.275198 -0.960755  0.376927 -0.685556
pak           D  0.680567 -1.563497 -0.566698 -0.242150 -2.130194
nep           E -0.333057  0.047365  1.462740  1.535029  1.510105
ch            F  0.149265 -1.078278  1.395472  1.787484  0.317194
bh            G  0.175387 -0.462506 -1.085801  0.639736 -1.548306
jpn           H -0.775762  0.995711 -1.933205  0.248531 -0.937493
ame           I -0.139474 -0.190656  0.448638 -0.992430  0.257982
rus           J -1.654571 -0.639723 -0.479420  0.311364 -1.119142